name: sync sec stock cik

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */4 * * *"

# on:
#   [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Sync sec ticker
        run: chmod +x ./scripts/*.py && for f in ./scripts/*.py ; do [ -x "$f" ] && [ ! -d "$f" ] && echo $f && python3 $f ; done
      - name: config git
        run: git config --global user.email "hemengzhi88@gmail.com"&&git config --global user.name "genkin-he"
      - name: submit
        run: chmod +x ./commit.sh && ./commit.sh
