name: sync sec stock cik

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */12 * * *"

# on:
#   [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Sync sec ticker
        run: chmod +x ./scripts/*.py && for f in ./scripts/*.py ; do [ -x "$f" ] && [ ! -d "$f" ] && echo $f && python3 $f ; done

      - name: config git
        run: git config --global user.email "hemengzhi88@gmail.com"&&git config --global user.name "genkin-he"
        
      - name: submit
        run: chmod +x ./commit.sh && ./commit.sh
