name: sync sec stock cik

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */1 * * *"

# on:
#   [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Run a one-line script
        run: chmod +x ./sync.sh && ./sync.sh
      # 配置 git
      - name: config git
        run: git config --global user.email "actions@gmail.com"&&git config --global user.name "ations"
      # 使用上面的 sh 脚本提交和推送
      - name: submit
        run: chmod +x ./commit.sh && ./commit.sh
